### ISSUE TITLE
Complete Make A Booking test (ID:0103)

### ISSUE THREAD

**Issue by ElliotW1999** [SE701ProjectGroup4/git-brunching#163]
![image](https://user-images.githubusercontent.com/48418365/77143923-715bfe80-6ae9-11ea-884d-8f0af8be2e40.png)

**Comment by NathanMills1** [comment]
Blocked by #246 
Currently no confirmation message appears when quitting the reservation process

**Comment by NathanMills1** [comment]
Test is now passing, moving to done and closing issue.
