### ISSUE TITLE
Complete Edit Booking test (ID:0302)

### ISSUE THREAD

**Issue by ElliotW1999** [SE701ProjectGroup4/git-brunching#166]
![image](https://user-images.githubusercontent.com/48418365/77144190-137be680-6aea-11ea-8978-b359ef2fa980.png)

**Comment by NathanMills1** [comment]
Blocked by #189

**Comment by NathanMills1** [comment]
Test is passing, moved to done.

**Comment by NathanMills1** [comment]
Test is passing, closing issue
