### ISSUE TITLE
Undefined booking reference

### ISSUE THREAD

**Issue by MingChen91** [SE701ProjectGroup4/git-brunching#168]
**Describe the bug**
When booking a table, at the final stage you get a message that booking reference: undefine.

**To Reproduce**
1. On landing page click any restaurants.
2. Proceed to make a booking as usual
3. See error 
![image](https://user-images.githubusercontent.com/48301693/77144759-96ea0780-6aeb-11ea-8163-5460c4cd3148.png)

**Expected behavior**
Booking reference should be a unique ID that is generated which can be used to edit booking.

**Possible Solution***
Below is the code which calls the /reservation endpoint. 
code snippet from /frontend/src/store/booking/bookingEpic.js
![image](https://user-images.githubusercontent.com/48301693/77144948-15df4000-6aec-11ea-8646-bf5db357ece2.png)

Currently, the tableID has been left as a hardcoded number. The tableID is a foreign key in the `RESERVATION` table of the database, and needs to exist in the `TABLE` table. So entering a tableID that doesn't exist in `TABLE.id` will throw an error. Currently there is no error handling that displays the error, instead it just should booking reference : undefined. This should be handled more gracefully and to fix this issue we need to:

-  Get all the tables that are available for the number of guests, restaurant and booking time.
-  Select one of them and use the ID for that table as the tableID in the code above.

An existing endpoint accomplishes this functionality, it needs to be called and the ID needs to be passed in. The endpoint is /reservation/available. 
Endpoint is in /backend/routes/reservation.js : 
![image](https://user-images.githubusercontent.com/48301693/77145192-b46ba100-6aec-11ea-9dae-f889fe36ad98.png)

**Comment by wryao64** [comment]
Changed the name to describe the bug for clarity
