### ISSUE TITLE
Adding capability to display different logos for each restaurant.

### ISSUE THREAD

**Issue by MingChen91** [SE701ProjectGroup4/git-brunching#169]
**User Story:**
As a backend dev, I want to add a column in the database under the `RESTAURANT` table for a path to an image file. This can be used by the frontend to display an appropriate restaurant logo image for the user.

**Acceptance Criteria:**
- [ ] Database column added
- [ ] Backend endpoint updated to reflect changes when adding a restaurant, and listing the restaurant details to include the path.

**Additional Context:**
Currently, the logo being displayed is hardcoded to alternate between two images.

**Comment by DragonMeme** [comment]
In addition to the path to the image. It is impractical to put images of the logos in `/frontend/public/images` when the frontend moves to production.
Possibly have the images hosted on a third party size (e.g https://imgur.com) and include the url path to the image, or store the image as a blob in the database.
