### ISSUE TITLE
One easier way to deploy the mysql database

### ISSUE THREAD

**Issue by WilbertGui** [SE701ProjectGroup4/git-brunching#174]
**User Story:**

As a contributor, I want one simple way to deploy the database so I do not have to figure out how to deploy the database.
or
As a contributor, I want one more clear document for the database deployment, so that I do not need to spend much time on it.

**Acceptance Criteria:**
One clearly wrote document with simple steps.
Clearly state possible problems and solutions.

**Additional Context:**

**Comment by yathu03** [comment]
LGTM, similar to #194

**Comment by jhsi517** [comment]
Marking this one as duplicate, #194 contains more specific info
