### ISSUE TITLE
Booking page error

### ISSUE THREAD

**Issue by WilbertGui** [SE701ProjectGroup4/git-brunching#175]
**Describe the bug**
The "next" operation is wrong when seats and time not available.

**To Reproduce**
1. Go to 'booking page'
2. Input one small number for "number of guests" 
3. When you choose time for the booking, you can find that the times are available, so does the "next" button. But if you change the "number of guests"  to a large number, you can find the times are not available, but the next button is still available. And when you press it, the page will jump to details page.

**Expected behavior**
1. The "next" button should only be available when the input of the number of guests and time are correct.
2. When it's unavailable, a hint should play to explain why you can not go to the next step.

**Screenshots**

![image](https://user-images.githubusercontent.com/39642674/78613649-804ff880-78c0-11ea-93fd-a49819d67e69.png)

**Comment by yathu03** [comment]
This is a similar issue to #193

**Comment by jhsi517** [comment]
@yathu03  i would say to keep both his one and #193 . This is a valid bug to fix. 

#193 will add further enhancements once this is completed.
