### ISSUE TITLE
Limitation for the input

### ISSUE THREAD

**Issue by WilbertGui** [SE701ProjectGroup4/git-brunching#176]
**User Story:**

As one user, I want the inputs in the booking/details page are limited so I can make sure I always input the right information for one booking.

**Acceptance Criteria:**

Wrong message or invalid next step when the contents of input are unavailable.
Such as, one email address should contain "@" symbol.

**Additional Context:**
One possible solution might be to use regular expression for the input.

**Comment by style0403** [comment]
Looks good I will look on to this issue :)

**Comment by Richardng12** [comment]
Fixed with PR #245
