### ISSUE TITLE
Restaurant Card Menu Button Hi-fi

### ISSUE THREAD

**Issue by maddiebeagley** [SE701ProjectGroup4/git-brunching#179]
**User Story:**

As a developer, I want to know what the restaurant cards on the main page of the site will look like when menus can be accessed from them so that I know what to work towards when developing this aspect of the UI. 

**Acceptance Criteria:**
- A hi-fi prototype for this UI component has been completed and added to the project wiki. 
- The hi-fi prototype includes the desired look of the menu button when it has been hovered over.

**Additional Context:**
This issue will be blocking for the ticket adding the menu button to restaurant cards as developers should wait for UI guides before completing this feature to avoid wasting effort.

**Comment by yathu03** [comment]
LGTM
