### ISSUE TITLE
Add Restaurant Card Menu Button

### ISSUE THREAD

**Issue by maddiebeagley** [SE701ProjectGroup4/git-brunching#180]
**User Story:**

As a user, I want to see how I can view the menu of a restaurant of my choice so that I can easily navigate to that restaurant's menu if I want. 

**Acceptance Criteria:**
- There is a menu button on each restaurant card on the main page
- Each menu button is styled consistently with the hi-fi prototype in the wiki including hover effects

**Additional Context:**
This ticket is blocked by: #179 
Currently, this button will not have any functionality, this is to be implemented by a later ticket when a menu popup is created.

**Comment by WilbertGui** [comment]
LGFM
