### ISSUE TITLE
Add dummy data for restaurant menus

### ISSUE THREAD

**Issue by jbea599** [SE701ProjectGroup4/git-brunching#183]
**User Story:**

As a developer, I want test data for menus in the database so I can validate the functionality of the menu popup and its associated features. 

**Acceptance Criteria:**
- [x] Multiple sets of data should be made to test both the single and multi-page menus
  * At least one single page menu and one multi-page menu
- [x] Data should be in an image format (jpg)
- [x] Appropriate field should be added to the database to contain this information

**Additional Context:**
This ticket is somewhat blocked by #185 , which will outline the required dimensions of the menu images.

**Comment by jhsi517** [comment]
@jbea599 please confirm if the blocked issue you're referring to is #185 :)
