### ISSUE TITLE
API for receiving menu information

### ISSUE THREAD

**Issue by jbea599** [SE701ProjectGroup4/git-brunching#184]
**User Story:**

As a developer I want an API to retrieve menus that are stored in the database so I can display this information on the menu pop-ups.

**Acceptance Criteria:**

* Can successfully call API and receive menu to be displayed

**Additional Context:**

* Menus are stored in the database as images (jpg)
* Blocked by #183 which sets up database to support menus and provides dummy data

**Comment by wryao64** [comment]
LGTM

**Comment by yfchen12** [comment]
Closed by PR #282
