### ISSUE TITLE
Restaurant menu popup hi-fi

### ISSUE THREAD

**Issue by mini** [SE701ProjectGroup4/git-brunching#185]
**User Story:**
As a developer, I want to know exactly what the menu pop up should look like so I can contribute to it in a consistent manner.

**Acceptance Criteria:**
* A hi-fi prototype is created and added to the project wiki.
* Needs to include restaurant title, a large panel for menu images, cancel button and book button.

**Additional Context:**
Blocks most issues that improve the menu popup

**Comment by jhsi517** [comment]
@mini please confirm if this is only blocking #186 :)

**Comment by mini** [comment]
[Done](https://github.com/SE701ProjectGroup4/git-brunching/wiki/Menu-Pop-up-Hi-Fi-Prototype)

@jhsi517 Sorry didn't get any notification about your comment, #186 is the main implementation ticket that the smaller features were blocked on.
