### ISSUE TITLE
Cancel booking process

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/git-brunching#190]
**User Story:**
As a user, I want some indication of how to return to the main menu from the restaurant booking screen, so that I can cancel a booking without submitting.

**Acceptance Criteria:**
[ ] Add cancel button to booking screen to cancel making an order
[ ] Cancel button must return the user to the landing page of the web app

**Additional Context:**
Button should be placed to the left of the next button on the booking screen

**Comment by tomatopaste202** [comment]
Maybe change the "so that" to "so that I can cancel a booking without submitting" or something along those lines.

Also, does the acceptance criteria need to be more detailed? For example, specifying that "the cancel button will bring the user back to the home screen"
