### ISSUE TITLE
Fix childish messages during reservation process

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/git-brunching#191]
**Describe the bug**
At multiple points during the booking process, certain messages are displayed which are not formal enough for a business booking system

**To Reproduce**
1. Go to the landing page
2. Click on any of the available restaurants to begin booking procedure
3. Select a time and date, and move to details screen
4. See error: On details, it reads "Tell me about yourself :P"
5. On confirmation screen it reads "Booking complete!!!!"

**Expected behavior**
On the details screen, the message should read "Enter contact details"
On the confirmation screen it should read "Booking Complete"

**Screenshots**
![image](https://user-images.githubusercontent.com/43223968/78722535-cc14a780-797d-11ea-8a0c-e1d94ccaf1a4.png)
![image](https://user-images.githubusercontent.com/43223968/78722566-db93f080-797d-11ea-8b81-d9a647629cfb.png)

**Comment by yfchen12** [comment]
Nice found.
