### ISSUE TITLE
Undefined booking reference

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/git-brunching#192]
**Describe the bug**
Once finished making a new reservation at a reference, on the complete booking page, the booking reservation is undefined.

**To Reproduce**
1. Go to any restaurant reservation page
2. Select a date and time
3. Go to next and enter user details
4. Confirm booking and arrive at confirmation page

**Expected behavior**
A unique booking reservation code should be generated upon completion of the booking and given to the user. This reservation code must match the format used for when entering booking IDs to edit.

**Screenshots**
![image](https://user-images.githubusercontent.com/43223968/78723164-0c285a00-797f-11ea-8b6c-92db73118ca0.png)

**Comment by mitchfaulcon** [comment]
I think this might already be an issue in #168, it looks like there might already be some progress towards fixing it in there too

**Comment by NathanMills1** [comment]
Yup you are correct, missed that one.
