### ISSUE TITLE
Display max bookable seats

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/git-brunching#193]
**User Story:**
As a user I want to know the maximum number of seats I can book in a reservation, so I can quickly tell if I will be able to make the booking or not

**Acceptance Criteria:**
- [ ] Upon selecting a number of people greater than the max available to book for a restaurant, an error message should appear explaining as much, and detailing the maximum allowable in a booking.
- [ ] Rather than having times all greyed out when selecting too many people, do not display them and show the error in its place

**Additional Information**
Blocked by #175

**Comment by jhsi517** [comment]
The first AC would be checked once bug stated in #175 is resolved. Otherwise, looks good to me :)
