### ISSUE TITLE
Improve setup instructions for database

### ISSUE THREAD

**Issue by JedLJRobertson** [SE701ProjectGroup4/git-brunching#194]
**Describe the change requested**
Setting up the database is currently mostly undocumented, and difficult for those without GCP and MySQL experience. 

This change would see better setup instructions for the database, with notes for special cases.

- [x] Make sure db setup is signposted in the getting started guide
- [x] Document how to setup a local MySQL instance on Windows using XAMPP
- [x] Document how to use an existing MySQL server
- [x] Document GCP setup

**Comment by yathu03** [comment]
LGTM

**Comment by JedLJRobertson** [comment]
Changes have been made to the Wiki.
