### ISSUE TITLE
Support different database names

### ISSUE THREAD

**Issue by JedLJRobertson** [SE701ProjectGroup4/git-brunching#196]
**User Story:**

As a developer/sysadmin/ops I want to change the database name so I can run a more flexible environment.

**Acceptance Criteria:**

- [ ] All functionality preserved when a db name other than 'restaurant_db' is specified

**Additional Context:**

Some SQL scripts are hardcoded to use the standard db name, fixing this should allow this.

**Comment by wryao64** [comment]
This is a useful issue!
