### ISSUE TITLE
Add restaurant reviews

### ISSUE THREAD

**Issue by yathu03** [SE701ProjectGroup4/git-brunching#197]
**User Story:**

As a user I want information about the restaurants and experiences of past customers. A section can be added for reviews that are available to the public.

**Acceptance Criteria:**

* Make a review button
* A review section pop up can be shown before the booking screen with a simple upvote/downvote system.

**Additional Context:**
Could otherwise be integrated into the menu pop up

**Comment by gargi-bansal** [comment]
Would this also be a backend feature as the reviews would have to be stored somewhere?

**Comment by jhsi517** [comment]
I think this one focuses on the front end. @yathu03 please also raise a related backend specific ticket if they are not in place :). 

Approving this ticket

**Comment by yfchen12** [comment]
Closed by pr #303
