### ISSUE TITLE
Able to Search for Existing Restaurants

### ISSUE THREAD

**Issue by jhsi517** [SE701ProjectGroup4/git-brunching#198]
**User Story:**

As a user, I want to be able to find a restaurant so that I can find restaurant that I'm thinking of.

**Acceptance Criteria:**

- [ ] Able to search for restaurant by typing phrases
- [ ] Able to display "none found" if there's no match with the input
- [ ] Able to only display restaurants that matches with what user have typed
- [ ] Able to begin the search by pressing "Enter"
- [ ] Able to begin the search by clicking the search icon

**Additional Context:**

**Comment by yfchen12** [comment]
LGTM

**Comment by HongShi10** [comment]
Would this issue also need front end development with the feature of pressing enter and clicking the search icon?

**Comment by jhsi517** [comment]
I have not reviewed the front-end code in detail yet. But I'm assuming that yes, there will be some minor front end dev required.

**Comment by jhsi517** [comment]
@HongShi10 would it be sufficient to add a front-end label...? The AC should be able to cover the connection between the backend and frontend .

**Comment by jhsi517** [comment]
Removing the front end part for this issue as it's more complicated than I originally anticipated. Will raise a ticket for front end. This has also address's Hong's concern
