### ISSUE TITLE
Group restaurants on homepage into categories

### ISSUE THREAD

**Issue by gargi-bansal** [SE701ProjectGroup4/git-brunching#200]
**User Story:**

As a user, I want to discover new restaurants so that I can make a booking at one of them, if I haven't already decided on a restaurant beforehand.

**Acceptance Criteria:**

- [ ] Create categories on home page such as 'Currently open', 'Popular', 'New' (and any other useful categories) in which restaurants appear.
- [ ] Can view all restaurants that fall under the relevant categories

**Additional Context:**
Blocked by: #258, #253

**Comment by wryao64** [comment]
Sounds good
