### ISSUE TITLE
Add time availability of the booking by calling the API 

### ISSUE THREAD

**Issue by style0403** [SE701ProjectGroup4/git-brunching#201]
**User Story:**
As a developer I want to display the availability of the booking time. 

**Acceptance Criteria:**

* Successfully show the time availability from the booking page. 

**Additional Context:**
* Blocked by issue #141. 
* Related to #178

**Comment by wryao64** [comment]
I don't quite understand this issue. Doesn't it already display the available times? (shown below)
![image](https://user-images.githubusercontent.com/27871855/79632482-9f4d6500-81b3-11ea-848a-3c0ee82a4a71.png)

**Comment by style0403** [comment]
I should have made it as a bug. At the moment you cannot make a booking when there is more than 2 guests.

**Comment by wryao64** [comment]
@style0403  see below
![image](https://user-images.githubusercontent.com/27871855/79632561-3e725c80-81b4-11ea-93d8-0aa529e17b8a.png)

I think this is something to do with a reloading issue

**Comment by style0403** [comment]
Thanks for the clarification :)
