### ISSUE TITLE
Connect front-end and back-end for reservations

### ISSUE THREAD

**Issue by HongShi10** [SE701ProjectGroup4/git-brunching#205]
As a developer, I want the front-end to be connected to be the back-end so I can retrieve reservation data 

**Acceptance Criteria:**

- [ ] Remove all mock data from RestarauntViewBookingPage

- [ ] Grab all reservation data from backend

**Additional Context:**
Currently, reservations only use mock data

**Comment by NathanMills1** [comment]
Just to note, PR #215 has a change effecting this issue.

> The get method /reservation/:reservationID had to have its path changed, as it was intercepting all get requests to /reservation. It was changed to /reservation/findreservation/:reservationID

**Comment by wryao64** [comment]
Passed to @ZianYangAng
