### ISSUE TITLE
Manually entering number of guests

### ISSUE THREAD

**Issue by tomatopaste202** [SE701ProjectGroup4/git-brunching#206]
**Describe the bug**
When typing the number of guests, user can input the letter “e” and use decimal points.

**To Reproduce**
1. Go to KFC
2. Click on the number of guests text fields
3. Type in “e” or a decimal number
4. The input will be allowed

**Expected behavior**
The app does not allow users to type in string or decimals

**Screenshots**

![bug2](https://user-images.githubusercontent.com/40707646/78743666-5d524100-79b3-11ea-9b78-8dafa9ac8172.png)

![bug](https://user-images.githubusercontent.com/40707646/78743601-3562dd80-79b3-11ea-9795-740dd0d1d435.png)

**Comment by WilbertGui** [comment]
@style0403  Similar issue as #176

**Comment by style0403** [comment]
> [176](https://github.com/SE701ProjectGroup4/git-brunching/issues/176)

Thanks, I will look on to this wit #176
