### ISSUE TITLE
Retrieve previous reviews

### ISSUE THREAD

**Issue by yathu03** [SE701ProjectGroup4/git-brunching#209]
**User Story:**

As a user I want to see previous reviews made by others at the restaurant.

**Acceptance Criteria:**

* Retrieve previously written reviews from the database
* Have an express router that enables CRUD operations for reviews

**Additional Context:**
Connected to #197 
Blocked by #210

**Comment by yfchen12** [comment]
LGTM. Updated it to be blocked by #210

**Comment by HongShi10** [comment]
Im assuming we just need the API call as this is only related to the backend?

**Comment by HongShi10** [comment]
Updated AC to match with backend criteria
