### ISSUE TITLE
Create a review table in database 

### ISSUE THREAD

**Issue by yfchen12** [SE701ProjectGroup4/git-brunching#210]
**User Story:**

As a developer, I want to have a review table in the database, so that the customers' reviews can be stored.

**Acceptance Criteria:**

- [x] A review table should be created
- [x] The review table should have the 'RestaurantID', 'Name' and 'Review' attributes
- [x] The foreign key of the review table should be 'RestaurantID' 
- [x] Update .sql dump file

**Additional Context:**
Related to #209

**Comment by jhsi517** [comment]
LGTM

**Comment by wryao64** [comment]
We want to associate a user with a review, but entries in the User table are currently restaurant owners. So I'll just add a field 'Name' for the reviewer to add a name
