### ISSUE TITLE
No of tables available for reservation is not visible

### ISSUE THREAD

**Issue by vaibhavnz** [SE701ProjectGroup4/git-brunching#212]
**User Story:**

As a user , I should be able to see tables available in a restaurant so that i can make a reservation.

**Acceptance Criteria:**

* Clicking on a restaurant and then proceeding with booking, system should display number of tables available in that particular time slot in that restaurant

**Additional Context:**

**Comment by jhsi517** [comment]
Please ensure the AC field is filled out so we can define the boundary of this feature :)

**Comment by NathanMills1** [comment]
Duplicate of #193, closed.
