### ISSUE TITLE
Modify and delete button doesn't function

### ISSUE THREAD

**Issue by vaibhavnz** [SE701ProjectGroup4/git-brunching#213]
when you click on the modify and delete button, it doesn't seem to be working

**To Reproduce**

1. On landing page click Restaurant button
2. you will see previous booking made by you 
3. click on the modify button.
4. Click on delete button
5. see bug

**Expected behavior**
user should be able to modify and delete the reservations made by them

**Screenshots**

**Additional context**

**Comment by jhsi517** [comment]
LGTM
