### ISSUE TITLE
Landing page searchbar covered

### ISSUE THREAD

**Issue by ZianYangAng** [SE701ProjectGroup4/git-brunching#217]
**Describe the bug**
On the landing page for the application, the serach bar is covered by the restaurants

**To Reproduce**
1. Run the project
2. Go to homepage

**Expected behavior**
The restaurants should not be covering the searchbar

**Screenshots**
![image](https://user-images.githubusercontent.com/41178640/79296504-b8de7a80-7f2f-11ea-85f5-c111e8149403.png)

**Additional context**

**Comment by DragonMeme** [comment]
Confirmed happening. Temporary fix is resizing the window, but introduces another bug where the logo does not expand in size after expanding the window (for Firefox at least).

**Comment by jhsi517** [comment]
I'm just curious, is this bug specific for firefox or... Have just tried with the Chrome and it seems fine

**Comment by mini** [comment]
I 'm able reproduce on FF and Chrome
