### ISSUE TITLE
Unable to obtain reservations made using reservationID through Swagger API.

### ISSUE THREAD

**Issue by DragonMeme** [SE701ProjectGroup4/git-brunching#220]
**Describe the bug**
Unable to retrieve existing reservation by ID when attempting to modify said booking.

**To Reproduce**
1. Start frontend and backend.
2. Make a reservation and obtain the reservationID.
3. Go to swagger and enter your ID in `GET /reservation/{reservationId}`.
4. Press execute (currently returns 404).

**Expected behavior**
Upon pressing execute, should return the booking API.

**Additional context**
Getting the booking through `GET reservations/{reservationID}` returned status 404.
![Screenshot from 2020-04-15 16-35-45](https://user-images.githubusercontent.com/48312022/79301545-fc3fe580-7f3d-11ea-9501-3de89013d516.png)

However the booking ID submitted exists in the database suggesting that the POST method that created the reservation works.
![Screenshot from 2020-04-15 16-40-33](https://user-images.githubusercontent.com/48312022/79301603-1c6fa480-7f3e-11ea-8af0-b50dff2ea89d.png)

Possibly related to #205 or duplicate.
Checked using PR #215 commit d01cfc9.

**Comment by wryao64** [comment]
I think this will be fixed in #205 so will mark this as duplicate for now

**Comment by wryao64** [comment]
Fixed with PR #251
