### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by wryao64** [SE701ProjectGroup4/git-brunching#227]
**Describe the bug**
Unable to run tests due to some bash error

**To Reproduce**
1. npm run dev
2. npm run mockTest
3. See error

**Expected behavior**
Test should run

**Screenshots**
![image](https://user-images.githubusercontent.com/27871855/79632166-ae331800-81b1-11ea-8333-f59addfe0d0c.png)

**Comment by HongShi10** [comment]
#228 Pr is linked to this issue

**Comment by Richardng12** [comment]
Should this be closed since #228 is merged?

**Comment by wryao64** [comment]
The fix for the above error (in VS Code) is to change the default shell to Bash. However, this results in a Docker error:
![image](https://user-images.githubusercontent.com/27871855/79632236-374a4f00-81b2-11ea-93f3-454da9bef1cd.png)

Unfortunately, my computer can't run Docker
