### ISSUE TITLE
Implement Search Bar Functionality

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/git-brunching#244]
**User Story:**
As a user, I want to be able to search for specific restaurants, in order to more easily find the restaurant I want to make a reservation for.

**Acceptance Criteria:**

- [ ] Upon Typing characters in the home screen search bar, restaurants should be filtered to only those containing the typed characters
- [ ] Search bar is case-insensitive
- [ ] All restaurants are stored front end after first get request, so that new requests are not required each time the search string is changed.

**Additional Context:**
Currently, the search bar UI has been created, but has no functionality associated with it.

**Comment by yathu03** [comment]
LGTM

**Comment by jhsi517** [comment]
Isnt this duplicate with #198 :o

**Comment by NathanMills1** [comment]
> Isnt this duplicate with #198 :o

Whoops in my quick search I somehow missed this one
