### ISSUE TITLE
Cancel Booking Confirmation

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/git-brunching#246]
**User Story:**

As a user, I want to be warned when I am exiting out of the booking process, so that I don't accidentally quit out halfway, losing my progress of filling in my details

**Acceptance Criteria:**

- [x] Upon pressing the back button, the Git Brunching logo, or the cancel button, during the reservation process, a pop up should be displayed to the user, asking them to confirm they want to leave the reservation process.
- [x] Upon pressing the yes option, the user should be redirected to the homepage.
- [x] If selecting no, the pop up should disappear, and users are able to carry on with the reservation process.

**Comment by jhsi517** [comment]
Looks good, removing review label :)
