### ISSUE TITLE
Create endpoint to get most popular restaurants and open restaurants

### ISSUE THREAD

**Issue by JainalGandhi** [SE701ProjectGroup4/git-brunching#253]
**User Story:**
As a developer I want endpoints and query to retrieve the most popular restaurants and the open restaurants so that they can be retrieved from the frontend and displayed on the homepage.

Popular restaurants is defined as the restaurants which have had the most bookings made (visitors) in the last month.

**Acceptance Criteria:**
* [ ] Endpoint made to retrieve the most popular restaurants.
* [ ] Endpoint made to retrieve the currently open endpoints.
* [ ] "Limit" query parameter included in endpoint so the frontend can decide how many restaurants to retrieve.

**Additional Context:**
* This is required for [200](https://github.com/SE701ProjectGroup4/git-brunching/issues/200)

**Comment by HongShi10** [comment]
Would this require a change in the database for the bookings? since we need someway of determining most popular

**Comment by JainalGandhi** [comment]
Using a join between the restaurant table and the bookings, then a group by on the restaurants and then summing the number of bookings per each group and ordering by this sum value would probably be sufficient for this issue (this matches the definition of popularity defined above. Are you okay with that definition @HongShi10 ?). 

If that's all okay then we could do it without having to change the database.

**Comment by jhsi517** [comment]
What @JainalGandhi has proposed is a viable solution to @HongShi10 's concern. Removing the needs review tag :)
