### ISSUE TITLE
Change restaurant tile to use restaurant's image stored in the database

### ISSUE THREAD

**Issue by JainalGandhi** [SE701ProjectGroup4/git-brunching#269]
**User Story:**
As a user, I want to be able to see an image of the restaurant so that I can decide whether to eat there.

Database and endpoint is set up to retrieve a unique image associated with the restaurant. This should be displayed to the user in the frontend.

**Acceptance Criteria:**

* [ ] Restaurant tiles display their unique image if the restaurant has one set in the database
* [ ] Will display image such as [this](https://live.staticflickr.com/5565/14703224506_f3a48c9c48_b.jpg) if restaurant in database does not have one set.

**Additional Context:**
The linked image is labelled as free for reuse so can be used by git-brunching.

**Comment by vaibhavnz** [comment]
lgtm
