### ISSUE TITLE
Booking times do not update straight away

### ISSUE THREAD

**Issue by mitchfaulcon** [SE701ProjectGroup4/git-brunching#272]
**Describe the bug**
When making a booking and the user inputs a number of guests, the times available do not update until the user clicks out of the input box. This could result in confusion for the user as they may not realise the restaurant is actually open.

**To Reproduce**
1. Start making a booking
2. Type in a number in the number of guests input field
3. Notice that the available times says 'Closed' instead of listing the timeslots

**Expected behavior**
The available times for that date and number of guests should show up

**Screenshots**
As the user types, the times are incorrect:
![image](https://user-images.githubusercontent.com/42291691/79809567-e9596500-83c4-11ea-951a-93eb3374280b.png)
Only after clicking away do the times update:
![image](https://user-images.githubusercontent.com/42291691/79809575-f1190980-83c4-11ea-91af-7bcce02224df.png)

**Comment by JainalGandhi** [comment]
Sounds good
