### ISSUE TITLE
Create endpoint to get newest restaurants

### ISSUE THREAD

**Issue by JainalGandhi** [SE701ProjectGroup4/git-brunching#276]
**User Story:**
As a developer I want an endpoint and query to retrieve the newest restaurants  so that they can be retrieved from the frontend and displayed on the homepage.

This requires adding a new "DateAdded" column to the restaurant table. The endpoint used to create restaurants should be altered accordingly. 

**Acceptance Criteria:**
* [ ] Endpoint made to retrieve the newest restaurants.
* [ ] "Limit" query parameter included in endpoint so the frontend can decide how many restaurants to retrieve.
* [ ] "DateAdded" column added to restaurant table and endpoint used to create restaurants sis altered accordingly. 

**Additional Context:**
Required for #200

**Comment by jhsi517** [comment]
sounds good :)
