### ISSUE TITLE
Confirm delete booking

### ISSUE THREAD

**Issue by gargi-bansal** [SE701ProjectGroup4/git-brunching#279]
**User Story:**

As a user/restaurant owner, I want to confirm that I would like to permanently delete a booking so that I don't accidentally remove a reservation that I wasn't supposed to delete.

**Acceptance Criteria:**
- [ ] A new popup screen asking to confirm or cancel deletion of a booking appears
- [ ] Clicking on cancel does not remove the booking
- [ ] Clicking on confirm permanently deletes the booking
- [ ] This is handled on both the "Edit Booking" Popup dialog accessible from the Homepage and the Reservations screen

**Additional Context:**

**Comment by jhsi517** [comment]
Sounds good to me :)
