### ISSUE TITLE
tableCapacity is undefined

### ISSUE THREAD

**Issue by Richardng12** [SE701ProjectGroup4/git-brunching#283]
**Describe the bug**
When accessing the bookings page, the tableCapacity in timeContainer is undefined as it is accessing fields in the db which don't exist

**To Reproduce**
1. Click on any restaurant to book
2. Page crashes

**Expected behavior**
Web app should still be functional

**Screenshots**
![image](https://user-images.githubusercontent.com/42757966/79823431-ea4fbe00-83e7-11ea-98dd-2b0b0eb9e833.png)

**Additional context**
Possibly lines 65 and 66 in TimeContainer.js need to be changed to fields that are in the bd (tableCapacity.minGuests, tableCapacity.maxGuests)

**Comment by yfchen12** [comment]
I think this is caused by the table name restaurant_db.table. Should be changed to restaurant_db.TABLE
