### ISSUE TITLE
Create documentation for Review and Menu API

### ISSUE THREAD

**Issue by HongShi10** [SE701ProjectGroup4/git-brunching#288]
**User Story:**

As a developer I want documentation for the Menu and Review API so I can easily tell what the requests are doing and what parameters are being used.

**Acceptance Criteria:**
* New wiki page for menu and review APIs
* Input parameters and output parameters for each request
* List of all requests that can be made
* List of all response numbers and the describing what the status codes mean

**Comment by jhsi517** [comment]
LGTM :)

**Comment by HongShi10** [comment]
Closing issue as it is completed
