### ISSUE TITLE
Display a default 'no menu' image for restaurants that don't have a menu

### ISSUE THREAD

**Issue by lolagarden** [SE701ProjectGroup4/git-brunching#297]
**User Story:**

As a user, I want to be made aware that a restaurant _doesn't_ have a menu, so I'm not waiting for a menu to load that doesn't exist.

**Acceptance Criteria:**

* An image is displayed which indicates to the user that the restaurant whose menu they are trying to view, doesn't have a menu.
* This image is **not** visible if a restaurant does have a menu image 

**Additional Context:**

**Comment by maddiebeagley** [comment]
Might also be good to add an AC about making sure this image is not visible if a restaurant **does** have a menu image
