### ISSUE TITLE
Update menu popup documentation to include google maps and web buttons

### ISSUE THREAD

**Issue by raghavgarg32** [SE701ProjectGroup4/git-brunching#302]
**User Story:**
As a developer, I want to see how the google maps and web buttons would look like and work on the menu popup so that when implementing them they are consistent with what was intended.

**Acceptance Criteria:**
- Documentation shows how the buttons will look like
- Documentation shows how these buttons will function
- Documentation shows the styling these buttons have

**Comment by maddiebeagley** [comment]
LGTM!

**Comment by jbea599** [comment]
Documentation updated here https://github.com/SE701ProjectGroup4/git-brunching/wiki/Menu-Pop-up-Hi-Fi-Prototype, closing issue
